"""empty message

Revision ID: 5b279765e26f
Revises: 04ebda51acc6
Create Date: 2021-04-24 22:50:43.142522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b279765e26f'
down_revision = '04ebda51acc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('userLikes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'userLikes')
    # ### end Alembic commands ###
